package: edit_modules
version: '1.0'
author: Benjamin Hacker
supportpage: benjamin-hacker.de
docspage: benjamin-hacker.de

page:
  title: 'Edit Modules'
  icon: 'rex-icon fas fa-wrench'
  perm: admin

requires:
  php:
    version: '>=7.0'
  redaxo: '>=5.0.0'
